FORMAT: 1A
HOST: https://mailcow.host/

# mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.

**This documentation is in outdated please view the API docs at https://demo.mailcow.email/api/ or at your own mailcow install by visiting /api/ **
